package starter.java;

public class Token_AuthenticationPage {
    public static final String authToken = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdXRob3JpemVkIjp0cnVlLCJleHAiOjE3MDI4OTQ2MDksIm5hbWUiOiJEci4gQ2hpa2EgTWV5bGl0YSwgU3AuQmVkYWgiLCJyb2xlIjoiZG9jdG9yIiwidXNlcl9pZCI6Ijc2ZmJhZDllLTVjOGYtNDQ5MC1iN2FhLThmZmJjYjRhMzcxMiJ9.ghfu168kJDf3MjZwRZ-UMbdifiOlAYmZcaLQFeWfYXA";

    public static final String authTokenAdmin = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdXRob3JpemVkIjp0cnVlLCJuYW1lIjoiIiwicm9sZSI6ImFkbWluIiwidXNlcl9pZCI6IjVjN2EwOWQ4LWU3MGItNDA5NC05MTFjLTZlYjc4N2I5Mzc2YiJ9.kLBZ0cgaazK0v4Ln6GffR9XOhgXkQoQxw2wHUQeC8yU";
}