<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Masuk Sebagai Dokter</name>
   <tag></tag>
   <elementGuidId>39d47626-4564-4be7-9a71-067737043508</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#login-as-doctor-button</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='login-as-doctor-button']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>21b0322e-c4a9-430d-af19-a2e69432e588</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>login-as-doctor-button</value>
      <webElementGuid>ae6d91b1-54d3-4635-b76f-8ffcb2fb8e78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>068accaf-f9dd-43be-a5d2-593e726a3dc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-btn css-2i2tap ant-btn-default ant-btn-background-ghost border-green-500 px-6 pb-8 pt-2 font-semibold text-green-500 hover:bg-green-500 hover:text-white 2xl:mt-6</value>
      <webElementGuid>b3294c77-298a-4348-bd22-6d9f405d7181</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Masuk Sebagai Dokter</value>
      <webElementGuid>50005989-54aa-4a19-a099-8597d46488f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;login-as-doctor-button&quot;)</value>
      <webElementGuid>6df5c657-dbba-4b07-9331-831545d89809</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='login-as-doctor-button']</value>
      <webElementGuid>82a29827-c971-429e-9f47-a256ee36113e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='content-landing-page']/section[2]/div/div/div/div/a[2]/button</value>
      <webElementGuid>1e826164-a0f3-420e-b1fb-44585ccc8917</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Gabung Bersama Kami'])[1]/following::button[1]</value>
      <webElementGuid>87d4e068-e146-4ad5-a004-e703ade9c071</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jadilah Bagian dari ReproHealth'])[1]/following::button[2]</value>
      <webElementGuid>a6818b6e-1378-4df1-9472-a25798bc8f72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Manfaat Bergabung Sebagai Dokter di ReproHealth'])[1]/preceding::button[1]</value>
      <webElementGuid>5d32f378-3154-4b9d-9f5d-96d54e630da9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]/button</value>
      <webElementGuid>c3d93ab3-2d4e-4fa4-90e5-a23d05061284</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'login-as-doctor-button' and @type = 'button' and (text() = 'Masuk Sebagai Dokter' or . = 'Masuk Sebagai Dokter')]</value>
      <webElementGuid>c90ddbd5-df1e-4fea-9435-ec375c2c9fb8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
