<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_email atau password yang anda masukan salah</name>
   <tag></tag>
   <elementGuidId>0b5c8f47-d02e-4b22-83f0-8604a42a8396</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.Toastify__toast-body > div</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='1']/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>18b1de65-fb26-40c5-a1b6-986714176a73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>email atau password yang anda masukan salah!</value>
      <webElementGuid>2b9f2204-e03e-48f6-8f6b-a51ff20a2abf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;1&quot;)/div[@class=&quot;Toastify__toast-body&quot;]/div[1]</value>
      <webElementGuid>3f5655e5-0732-4dbd-8061-f225d5a23537</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='1']/div/div</value>
      <webElementGuid>33c10baa-599c-45f7-a70d-b8eeaafd4395</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Abaikan'])[1]/preceding::div[1]</value>
      <webElementGuid>b08d58a8-ba03-4ae9-a5c6-82255a13f8aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Masuk ke Akun Anda!'])[1]/preceding::div[3]</value>
      <webElementGuid>d20211fb-6e02-4fd8-8a29-d41483167f56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='email atau password yang anda masukan salah!']/parent::*</value>
      <webElementGuid>dfdad93d-c018-4dbe-8e36-be89b8b7c227</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div</value>
      <webElementGuid>8f9e7684-adce-4165-847d-da1b72144bae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'email atau password yang anda masukan salah!' or . = 'email atau password yang anda masukan salah!')]</value>
      <webElementGuid>7f681cec-da27-4a4f-a6b4-b329acdb032b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
